version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
  app_back:
    image: back
    build:
      context: ./parsing/
      dockerfile: Dockerfile
    command: sh -c "python main.py"
    volumes:
      - .:/code
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    depends_on:
      - db

  app_front:
    image: front
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd store && python manage.py migrate && echo 'from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin\")' | python manage.py shell && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    depends_on:
      - db