version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
  app_back:
    build:
      context: ./parsing/
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    depends_on:
      - db

  app_front:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd store && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
    depends_on:
      - db