# Generated by Django 4.2.7 on 2023-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.BigIntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'history_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ean', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=13, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=16, null=True)),
                ('sizechart', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
